# -*- coding: utf-8 -*-
"""TerrorismDash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhkaAo2iuh5sTGAC-qZBPk8MqSQC1SJB
"""

# ==================================================
# INDIA INCIDENT GEO-ANALYTICAL DASHBOARD v2.0
# ==================================================

import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium
from folium.plugins import HeatMap, TimestampedGeoJson
import networkx as nx
from pyvis.network import Network
import tempfile
from textblob import TextBlob
from bs4 import BeautifulSoup
import requests
from fake_useragent import UserAgent
import feedparser
from datetime import datetime

# ==================================================
# CONFIG
# ==================================================
st.set_page_config(page_title="Raksha Geo-Analytical Terrorism Portal", layout="wide")
st.title("Raksha Geo-Analytical Terrorism Portal")

# ==================================================
# LOAD DATA
# ==================================================
@st.cache_data
def load_data():
    df = pd.read_csv("incidents.csv")
    df.columns = df.columns.str.strip().str.replace(" ", "_").str.replace("/", "_").str.replace("-", "_")
    df = df.dropna(subset=["Latitude", "Longitude"])  # Remove rows with missing coordinates
    return df

df = load_data()

# -------------------------
# ==================================================
# TABS
# ==================================================
tab1, tab2, tab3 = st.tabs(["Visualisation", "State-wise Data", "Geo-Analytics"])

# ==================================================
# PAGE A: VISUALISATION
# ==================================================
with tab1:
    st.subheader("Incident Map")
    col1, col2 = st.columns([1,4])
    with col1:
        years = sorted(df["Year"].dropna().unique())
        selected_year = st.selectbox("Select Year", ["All"] + years)
        filtered_df = df.copy()
        if selected_year != "All":
            filtered_df = filtered_df[filtered_df["Year"] == int(selected_year)]
        incident_names = sorted(filtered_df["Incident_Name"].dropna().unique())
        selected_incident = st.selectbox("Select Incident", ["All"] + incident_names)
        if selected_incident != "All":
            filtered_df = filtered_df[filtered_df["Incident_Name"] == selected_incident]
    with col2:
        if filtered_df.empty:
            st.warning("No data for selection")
        else:
            center_lat = filtered_df.iloc[0]["Latitude"]
            center_lon = filtered_df.iloc[0]["Longitude"]
            zoom = 8 if selected_incident != "All" else 5
            m = folium.Map(location=[center_lat, center_lon], zoom_start=zoom, tiles="CartoDB positron")
            for _, row in filtered_df.iterrows():
                popup_html = f"""
                <b>Incident:</b> {row['Incident_Name']}<br>
                <b>Date:</b> {row['Date']}<br>
                <b>Location:</b> {row['Specific_Location']}, {row['State_UT']}<br>
                <b>Description:</b> {row['Description']}<br>
                <b>Killed:</b> {row['Killed']}<br>
                <b>Injured:</b> {row['Injured']}<br>
                <b>Status:</b> {row['Case_Status']}<br>
                <b>Perpetrator:</b> {row['Perpetrator_Group']}<br>
                """
                folium.Marker(location=[row["Latitude"], row["Longitude"]],
                              tooltip=row["Incident_Name"],
                              popup=folium.Popup(popup_html, max_width=350)).add_to(m)
            st_folium(m, width=1100, height=600)

# ==================================================
# PAGE B: STATE-WISE DATA
# ==================================================
with tab2:
    st.subheader("State-wise Overview")
    state = st.selectbox("Select State/UT", sorted(df["State_UT"].dropna().unique()))
    state_df = df[df["State_UT"] == state]
    col1, col2 = st.columns([2,3])
    with col1:
        st.markdown("### Active Perpetrator Groups")
        st.dataframe(state_df["Perpetrator_Group"].value_counts().rename("Count"))
        st.markdown("### Major Incidents")
        st.dataframe(state_df[["Year","Incident_Name","Killed","Injured"]])
    with col2:
        m_state = folium.Map(location=[state_df["Latitude"].mean(), state_df["Longitude"].mean()],
                             zoom_start=6, tiles="CartoDB positron")
        for _, row in state_df.iterrows():
            folium.Marker(location=[row["Latitude"], row["Longitude"]],
                          tooltip=row["Incident_Name"]).add_to(m_state)
        st_folium(m_state, width=900, height=550)

# ==================================================
# PAGE C: ANALYTICS & OSINT
# ==================================================
with tab3:
    st.subheader("Geo Analytics")
    incident = st.selectbox("Select Incident", sorted(df["Incident_Name"].dropna().unique()))
    group = df[df["Incident_Name"]==incident]["Perpetrator_Group"].iloc[0]

    # Toggle layers
    show_hotspot = st.checkbox("Show Hotspot Layer")
    show_temporal = st.checkbox("Show Temporal Animation")
    show_network = st.checkbox("Show Network Graph")


    # -------------------------
    if show_hotspot:
        st.markdown("### Hotspot Layer")
        heat_data = df[["Latitude","Longitude"]].dropna().values.tolist()
        m_hot = folium.Map(location=[22.5, 80.0], zoom_start=5, tiles="CartoDB positron")
        HeatMap(heat_data, radius=18, blur=15).add_to(m_hot)
        st_folium(m_hot, width=1100, height=500)

    if show_temporal:
        st.markdown("### Temporal Animation")
        features = []
        for _, row in df.iterrows():
            features.append({
                "type":"Feature",
                "geometry":{"type":"Point","coordinates":[row["Longitude"], row["Latitude"]]},
                "properties":{"time":f"{row['Year']}-01-01","popup":row["Incident_Name"]}
            })
        m_time = folium.Map(location=[22.5, 80.0], zoom_start=5, tiles="CartoDB positron")
        TimestampedGeoJson({"type":"FeatureCollection","features":features},
                           period="P1Y", add_last_point=True, auto_play=False, loop=False,
                           date_options="YYYY", time_slider_drag_update=True).add_to(m_time)
        st_folium(m_time, width=1100, height=500)

    if show_network:
        st.markdown("### State–Group–Incident Network")
        G = nx.Graph()
        for _, row in df.iterrows():
            G.add_edge(row["State_UT"], row["Incident_Name"])
            G.add_edge(row["Incident_Name"], row["Perpetrator_Group"])
        net = Network(height="600px", width="100%", notebook=False)
        net.from_nx(G)
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".html")
        tmp.close()
        net.save_graph(tmp.name)
        with open(tmp.name, "r", encoding="utf-8") as f:
            st.components.v1.html(f.read(), height=600)